apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api-image
  template:
    metadata:
      labels:
        app: weather-api-image
    spec:
      containers:
      - name: weather-api-image
        image: christopherregistry.azurecr.io/base-image:latest
        ports:
        - containerPort: 80
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: secret
                key: API_KEY