apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    service: test
spec:
  selector:
    app: weather-api-image
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
